meateam/api-gateway

download.go
file.go
go.mod
go.sum
main.go
router.go

Seems to be working - waiting to test with upload with file service

---

README.md
router.go
upload.go

file upload now saves uploaded file full name

---

file.go
go.mod
go.sum
pipeline.yaml

implemented get files by folder and user

---

upload.go

When any error occurs then the upload is aborted and the parts that have finished uploaded up until the error occurrance are deleted.
Now also delete an upload from the file-service when completing or aborting an upload.

added per-part upload error handling and client connection disconnect

---

.vscode/launch.json
main.go
router.go

added configuration route for web-ui

---

.vscode/launch.json
docker-compose.yml
main.go
router.go

remove unused api route config and update docker-compose.yml

---

file.go
upload.go

map grpc status code to http from file-service responses

---

docker-compose.yml
main.go
router.go

add configuration for apm in UI

---

go.mod
go.sum

update elasticsearch-logger to v1.1.2

---

auth.go

changed auth redirect from being permanent to being temporary

---

.vscode/launch.json
upload.go

disable apm capture body and handle EOF error from stream.Send

---

server/router.go

added auth url to config route

---

docker-compose.yml
go.sum
server/router.go
server/server.go

Signed-off-by: Yonatan <yonatald@gmail.com>

add support-link configuration

---

upload/upload.go
user/user.go

normalized

---

upload/upload.go

reduce MaxPartUploadSize from 5GB to 500MB

---

go.mod
go.sum
permit/permit.go

Signed-off-by: Yonatan <yonatald@gmail.com>

adds fileName to the permit request

---

docker-compose.yml
oauth/oauth.go
server/auth/auth.go
server/router.go
server/server.go
user/user.go

Signed-off-by: shahar-y <shya95@gmail.com>

more fixes

---

server/auth/auth.go
server/router.go
server/server.go

feat: add auth startegy for docs add authentication strategy for Docs

---

docker-compose.yml
server/router.go
server/server.go

new configuration field for the ui. 
WHITE_LIST_TEXT -> explains to the user about the approver white list

feat: add new env

---

upload/upload.go

Reverts meateam/api-gateway#165
The commit did not fix the issue.

Revert "Fix/file name"

---

server/auth/auth.go

Quick bugfix to develop created by metrics PR by @yonatandt

fix jwt filde fields do not exist

---

server/health.go
server/router.go

So far, every service which failed the healthcheck also failed the entire system.
I added the differentiation between the fatal services that should fail the system and those who shouldn't.
Closes #159 
Signed-off-by: shahar-y <shya95@gmail.com>

Added differentiation for non-fatal services

---

dropbox/dropbox.go
file/file.go
generate-proto.sh
go.mod
go.sum

Added pagination
Signed-off-by: shahar-y <shya95@gmail.com>

added pagination query params

---

CHANGELOG.md
Dockerfile
go.mod
go.sum
permission/permission.go

Signed-off-by: shahar-y <shya95@gmail.com>

fixed bug cargo same from to

---

CHANGELOG.md
file/file.go

* add failed and succesful file in getsharedfile
* Update CHANGELOG.md

add failed and succesful file in getsharedfile (#239)

---

file/file.go

Important change when doing rollback when there is an error creating copy

fix rollback on copyobject
